### ISSUE TITLE
CarveLibWrapper - Build Problems

### ISSUE THREAD

**Issue by martin-loucka** [Maghoumi/CarveSharp#1]
Hello 

I would like to use your wrappers but I have a problem to build the C++ project.

I am getting following errors:

LNK2001	unresolved external symbol "__declspec(dllimport) char const * __cdecl std::_Winerror_map(int)" (__imp_?_Winerror_map@std@@YAPEBDH@Z)

Does it look familiar?
Would it be eventually possible to get the DLL Wrapper file.

Thanks
Martin

**Comment by Maghoumi** [comment]
What version of Visual Studio are you using?

**Comment by martin-loucka** [comment]
VS 2015; Windows 8.1; Build for 64Bit

**Comment by Maghoumi** [comment]
The project's solution is for VS 2013 at the moment (also mentioned at the bottom of the README.md file). I've had plans to update it to VS 2015 for some time, but I haven't had much time. I will do my best to set aside some time and update things. In the mean time, would you be able to use it with VS 2013?

**Comment by martin-loucka** [comment]
Yes!!! It worked prefectly. You can close this issue. Thank you!
