### ISSUE TITLE
Licensing change to MIT?

### ISSUE THREAD

**Issue by fred-rpc3d** [Maghoumi/CarveSharp#3]
Hello
Your nice piece of software is based on the Carve library.
The owner of Carve has changed the license from GPL to MIT.
You can check here
https://github.com/folded/carve

I would like to use Carve in .Net, maybe in a commercial application.
Can you change also the license of CarveSharp to MIT.

Thank you

**Comment by Maghoumi** [comment]
Hello @fred-rpc3d,
Glad to hear that you found my library useful. I have no objection to change the license to MIT.
Let me investigate a bit. I will update you over here.

**Comment by Maghoumi** [comment]
@fred-rpc3d License changed.

Don't forget to give the repository a star if you find it useful!

Closing this issue
